@startuml
skinparam defaultTextAlignment center
skinparam sequenceMessageAlign left

!include <tupadr3/common>
!include <tupadr3/font-awesome/mobile>
!include <tupadr3/font-awesome-5/charging_station>

participant "<$mobile>\nClient" as GSM
box "<$charging_station>\nGeneric Service Server" 
participant "Command (0xDD)" as Command
participant "Status (0xDE)" as Status
participant "Data (0xDF)" as Data
end box
autonumber
GSM -> Command: Write [Badge:Add badge in MAX charging mode (0x3002)]
autonumber stop
return error code
...Wait until the charger is ready to add a badge...
autonumber resume
GSM <<- Status: Notify [Badge:WAIT_ADD(0x3002)]
...Wait until the user has presented the new badge...
alt successful case
autonumber resume
  GSM <<- Status: Notify [Badge:ADDED(0x3008)]
  GSM -> Data: Read the UID
  autonumber stop
  return UID
else duplicate case
autonumber resume
  GSM <<- Status: Notify [Badge:EXISTS(0x3009)]
end
@enduml