@startuml
skinparam defaultTextAlignment center
skinparam sequenceMessageAlign left

!include <tupadr3/common>
!include <tupadr3/font-awesome/mobile>
!include <tupadr3/font-awesome-5/charging_station>

participant "<$mobile>\nClient" as GSM
box "<$charging_station>\nGeneric Service Server" 
participant "Command (0xDD)" as Command
participant "Status (0xDE)" as Status
participant "Data (0xDF)" as Data
end box
autonumber
GSM -> Command: Write [Config:Config Set(0x5001)]
autonumber stop
return error code
...Wait until the charger is ready to accept data...
autonumber resume
GSM <<- Status: Notify [Config:READY(0x5001)]
GSM -> Data: Write Config_1_0 or Config_1_1 data 
autonumber stop
return error code
...Wait for data to be written...
autonumber resume
GSM <<- Status: Notify[Config:SUCCESS(0x5002)]
@enduml